Convolutions tasks divided into different files
SRA-VJTI/Pixels_Seminar pull request #123
Opened 2024-02-20 23:05 UTC by AryanNanda17

This issue involves refactoring the provided convolution code into three separate files, each focusing on a specific aspect of convolution operations, and creating a separate folder for benchmarking the results of each file.
Resolved issue #120

2024-02-20 23:08 UTC, AryanNanda17 commented
@PritK99, please checkout the PR and let me know if any change is required.

2024-02-21 14:20 UTC, PritK99 commented
Why are folders such as ```/src``` and ```/include``` a part of ```/benchmark``` directory?  The idea was to just create a new folder ```/benchmark``` to deal with the time features.

2024-02-21 18:34 UTC, AryanNanda17 commented
In the benchmarks folder time taken by each convolution is also being printed.  In order to Benchmark(time taken by convolution operation), we would have to perform convolution, so the folders ```/src``` and ```/include``` are important.

2024-02-22 14:46 UTC, advait-0 commented
@AryanNanda17 please add the usage instructions to run each file in the sub-folder readme.

2024-02-23 00:49 UTC, AryanNanda17 commented
@advait-0, I made the required changes please check it out.

2024-02-23 18:16 UTC, aPR0T0 commented
Hello @AryanNanda17, Please add benchmarks to each file or remove them from the separable convolutions as they all should have a common standard. The point of the benchmark here is to understand the reason behind the use of separable convolutions

2024-02-23 18:16 UTC, aPR0T0 requested changes
Please add / remove benchmarks

2024-02-23 18:50 UTC, AryanNanda17 commented
> Hello @AryanNanda17, Please add benchmarks to each file or remove them from the separable convolutions as they all should have a common standard. The point of the benchmark here is to understand the reason behind the use of separable convolutions

Hello @aPR0T0, could you please elaborate on this?
Because from what I understand issue #120 aims to make the code easier. So, I have separated all three approaches of convolutions in our case into three different files without benchmarks. For benchmarks, I have created a separate folder ```/benchmarks```
<img width="1223" alt="Screenshot 2024-02-24 at 12 19 07 AM" src="https://github.com/SRA-VJTI/Pixels_Seminar/assets/125150482/7ce49aa7-0d54-454f-b09b-0f91e34f7966">
The benchmarks folder benchmarks all three types of convolutions in our case!

2024-02-23 18:59 UTC, AryanNanda17 commented
> Sure @AryanNanda17 , makes sense then. Great work!
> 
> Just a small change, add benchmark ka example execution in readme

Thanks!

2024-02-23 19:20 UTC, AryanNanda17 commented
@aPR0T0, I added the results of Benchmarks in Readme. 
Please check it out.

2024-02-24 03:39 UTC, SuperChamp234 requested changes
<img width="315" alt="Screenshot 2024-02-24 at 9 05 03 AM" src="https://github.com/SRA-VJTI/Pixels_Seminar/assets/40035606/0b3a2a18-8541-490f-9c0a-e016e0073ac5">


Why does the benchmarking folder contain the same files from the parent folder?

Ideally, the benchmarking folder should just have a file that will use the convolutions demonstrated in it’s parent folder and show the difference. Different files for each of the convolutions is not necessary.

2024-02-24 03:39 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/benchmarks/README.md
> +make SRC=main.cpp link=src/convolution.cpp   # Use make to build the project
Can’t find a `main.cpp` maybe this should be `native.cpp`

2024-02-24 03:39 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/benchmarks/Makefile
Looks good to me

2024-02-24 03:39 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/convolutionUsingOpenCV.cpp
Looks Good to me

2024-02-24 03:39 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/naive.cpp
looks good to me!

2024-02-24 03:39 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/separableConvolutions.cpp
Looks good to me!

2024-02-24 03:40 UTC, SuperChamp234 commented
Please make the change of removing unnecessary files and merge the benchmarking code into one file @AryanNanda17. Good job so far!

2024-02-24 06:57 UTC, AryanNanda17 commented
> Please make the change of removing unnecessary files and merge the benchmarking code into one file @AryanNanda17. 

Hello @SuperChamp234!
- In issue #120 , @PritK99 suggested to make three separate files for each type of convolution and create a separate folder to benchmark the results of **each convolution file**. If we merge all three convolution files into one code, the code would become hard as before. But our goal here is to enhance code modularity, readability, and maintainability by isolating different functionalities into distinct files.

2024-02-24 08:29 UTC, aPR0T0 commented
> > Please make the change of removing unnecessary files and merge the benchmarking code into one file @AryanNanda17.
> 
> Hello @SuperChamp234!
> 
>     * In issue [Refactoring Convolution Filtering #120](https://github.com/SRA-VJTI/Pixels_Seminar/issues/120) , @PritK99 suggested to make three separate files for each type of convolution and create a separate folder to benchmark the results of **each convolution file**. If we merge all three convolution files into one code, the code would become hard as before. But our goal here is to enhance code modularity, readability, and maintainability by isolating different functionalities into distinct files.

Hello @AryanNanda17 , that's right we need to simplify the code

Just restructure the directories as ->
1. benchmark
2. include
3. src
4. assets
other files

and inside benchmark just keep cpp files, this way the folder remains generic

2024-02-24 09:07 UTC, AryanNanda17 commented
@aPR0T0, I made the changes. Please check it out.

2024-02-24 09:31 UTC, aPR0T0 approved these changes
LGTM!
Great work @AryanNanda17 !

2024-02-24 12:38 UTC, SuperChamp234 approved these changes

2024-02-24 12:38 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/README.md
looks good to me!

2024-02-24 12:38 UTC, SuperChamp234 commented on 4_cv_basics/4_convolutions_filtering/benchmarks/convolutionUsingOpenCV.cpp
looks good to me!

2024-02-24 12:38 UTC, merged