#129 issue : Fixed
SRA-VJTI/Pixels_Seminar pull request #130
Opened 2024-10-29 20:20 UTC by SanyamGarg12

Added setup.sh as an alternative of MakeFile and updated readme accordingly.

2024-10-31 11:54 UTC, SanyamGarg12 commented
@NachtSpyder04

2024-11-03 11:45 UTC, NachtSpyder04 requested changes
You have contributed to an already existing README.md. Make sure to inspect how headings and other information are in which format rather than copy-pasting your work without cross-checking.

2024-11-03 11:45 UTC, NachtSpyder04 commented on README.md
> +I'll fix the Markdown formatting in your README.md file to make it clearer and more consistent.
??

Sounds AI-Generated
not needed in the README, remove it

2024-11-03 11:45 UTC, NachtSpyder04 commented on README.md
> +# Installation Guide
Redundant line, heading is already given on line 54

2024-11-03 11:45 UTC, NachtSpyder04 commented on README.md
> +## Clone SRA-VJTI's Pixel Repository
follow the given format for headings, I would suggest to revert the headings

2024-11-03 11:45 UTC, NachtSpyder04 commented on README.md
> +## Change Directory
same, format issue

2024-11-03 11:50 UTC, NachtSpyder04 requested changes
How should I test your script? you have not mentioned it in the description

Update your description for the same (a Dockerfile will be preferable)

2024-11-03 11:50 UTC, NachtSpyder04 commented on setup.sh
> +        sudo apt-get install libopencv-dev libsdl2-2.0-0 libsdl2-image-dev libsdl2-dev -y
add a line to install 'build-essential' package (already mentioned in #129 ) for ubuntu as well as similar command for other OSs

2024-11-03 11:58 UTC, NachtSpyder04 commented
Update your PR title as well; it is unclear to those who are not aware of this issue.

2024-11-04 21:15 UTC, SanyamGarg12 commented
Thank you for reviewing my fixes! This is my first contribution, so I wasn’t yet familiar with some of these basics. I've also updated the README while keeping the original format intact.

To test the project setup, you can create a new virtual environment and run the bash script I added (without using make install). Instructions are included for guidance.

2025-02-13 07:31 UTC, AryanNanda17 commented
@SanyamGarg12, your Bash script doesn't fix #129.
It has issues. Please read the issue clearly, it states to download `git` , `make`, and other essentials before running the make command.

2025-03-07 19:54 UTC, AryanNanda17 commented
Thank you for your effort, but this issue has already been resolved by #131. We appreciate your contribution!

2025-03-07 19:54 UTC, closed without merging