opencv overview
SRA-VJTI/Pixels_Seminar pull request #69
Opened 2023-02-20 14:38 UTC by Om-Doiphode

Converted python code snippets of opencv overview to C++.
Following code files were made:
1) Reading and writing images
2) Blending
3) Masking
4) Object detection
5) Contours
6) Resizing

Co authored by @vrnimje

2023-02-21 09:41 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/masking/masking.cpp
> +    // Getting the height, width and number of channels of the image
Avoid writing comments in first_person

2023-02-21 09:42 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/masking/masking.cpp
> +    // I want to put logo on top - left corner, So I create a ROI
Same case here

2023-02-21 09:48 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/masking/masking.cpp
> +    // Cropping the img1 with (0,0) as the top left corner and (rows,cols) as the bottom right corner
Write more concise comments . You can explain this in the README

2023-03-09 04:09 UTC, Ris-Bali commented
Is this pr ready for review ?

2023-03-09 04:16 UTC, vrnimje commented
Yes @Ris-Bali

2023-03-09 20:29 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/masking/masking.cpp
> +    bitwise_and(roi, roi, img1_bg, mask);
Add a readme expalining what masking is and some images

2023-03-09 20:32 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/contours/contours.cpp
> +}
Add a readme for contours too

2023-03-09 20:33 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/blending/blending.cpp
> +    waitKey(0);
Can you add a comment here to state what is addweighted doing (i.e. blends img1 and img2).

2023-03-10 14:55 UTC, Ris-Bali commented on 4_cv_basics/8_opencv_overview/README.md
> +
Can you divide this readme (i.e. separate readme for each topic)

2023-03-22 10:06 UTC, amanchhaparia requested changes
- Add a `table of content` in the readme.
- Make a consistent use of `OpenCV`, instead of OpenCv/Open CV.
- Add a new line in files where required.

2023-03-22 10:06 UTC, amanchhaparia commented on 4_cv_basics/8_opencv_overview/README.md
> +## Expected Results
Place the content of `Expected Results` in their specific  topic sections

2023-03-22 10:06 UTC, amanchhaparia commented on 4_cv_basics/8_opencv_overview/README.md
> +<th colspan="2" style="text-align:center"> MORPHOLOGICAL OPERATIONS </th>
Create a section for Morphological Operations as well.

2023-03-22 10:06 UTC, amanchhaparia commented on 4_cv_basics/8_opencv_overview/grayscale/grayscale.cpp
> +    return 0;
Add comments

2023-03-24 04:53 UTC, amanchhaparia requested changes
@Om-Doiphode, What is the need of the blob detection jupyter notebook in this PR?

2023-03-25 05:51 UTC, amanchhaparia requested changes
- Revert the changes made in root Makefile
- Move the assets folder under the opencv_overview folder instead
- Add `table of content` in the root readme of opencv_overview folder.
- Move the long table of the functions and its description at the end or divide in another readme

2023-03-27 13:34 UTC, amanchhaparia requested changes
- No need to modify the root `Makefile`.
- The scope of the PR should be restricted to `opencv_overview` folder. Do not make unnecessary changes with rest of the folder.

2023-03-28 11:37 UTC, amanchhaparia commented
@Om-Doiphode, why you are unnecessary changing the contents of the other folders. Kindly restrict the commits of this PR to the opencv folder only

2023-03-28 12:01 UTC, closed without merging