Code for blob detection and readme
SRA-VJTI/Pixels_Seminar pull request #81
Opened 2023-02-26 19:10 UTC by Dishie2498

Made changes as per the reviews given. Code same as previously used python one.

2023-02-26 20:15 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +    int counter = 0;
Remove unused variables.

2023-02-26 20:17 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +            counter++;
Remove from here as well.

2023-02-26 20:18 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +    // cout << "Medians: " << h << " " << s << " " << v << endl;
Remove unwanted comments.

2023-02-26 20:20 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +    ///////////////// Median Blur //////////
Add a line-space

2023-02-26 20:20 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +    //////////////////////////
Add line space

2023-02-26 20:21 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +        area=contourArea(contours[i]);
Provide proper formatting.

2023-02-26 20:21 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +    int count=0;int largest=0;
add line gap between declaration of variables

2023-02-26 20:22 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/readme.md
> +```
You can use ```cpp to show cpp code, follow same for below code blocks as well.

2023-02-26 20:33 UTC, Dhruv454000 commented on 4_cv_basics/7_blob_detection/main.cpp
> +        count++;
Remove count++

2023-02-28 15:12 UTC, Dhruv454000 commented
Make changes in readme as per the new code, @amanchhaparia can you have a final look, I have tested the code and is working well.

2023-02-28 16:18 UTC, amanchhaparia requested changes
Add comments in the code as the requirement.

2023-02-28 16:18 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/Makefile
> +output: main.cpp
instead of `output` can be renamed as `blob_detection`

2023-02-28 16:18 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/main.cpp
> +double median(vector<double> vec)
Add a space before function

2023-02-28 16:18 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/main.cpp
> +tuple<double, double, double> getMedianPixelValues(Mat img)
Add a space

2023-02-28 16:18 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/main.cpp
> +int main()
Add space before `main()`

2023-02-28 16:18 UTC, amanchhaparia commented
@Dhruv454000, thanks for the review ping me once the above changes and readme is updated!

2023-03-23 16:46 UTC, closed without merging