Content for Build Systems
SRA-VJTI/Pixels_Seminar pull request #84
Opened 2023-03-23 09:38 UTC by PritK99

1) Merged both the readme into a single Readme 
2) Added a table of contents

2023-03-23 11:15 UTC, amanchhaparia commented
@PritK99, kindly update the table of content similar to [this](https://github.com/SRA-VJTI/Pixels_Seminar/tree/dev/4_cv_basics/4_convolutions_filtering#table-of-contents)

2023-03-23 11:20 UTC, amanchhaparia requested changes

2023-03-23 11:20 UTC, amanchhaparia commented on 2_build_systems/readme.md
> +    * Building
Use appropriate terminologies.

2023-03-26 07:39 UTC, SuperChamp234 commented
I've removed the build target since the project doesn't need it, and the root makefile simply helps with the opencv and dependency install. Readme was also updated for the same, please review.

2023-03-27 13:29 UTC, amanchhaparia approved these changes

2023-03-27 13:29 UTC, merged