Adding code for blob detection and readme
SRA-VJTI/Pixels_Seminar pull request #85
Opened 2023-03-23 11:02 UTC by Khushi-Balia

2023-03-23 11:44 UTC, amanchhaparia requested changes
@Khushi-Balia, requesting the below changes.
- Add table of content in the Readme
- Rename readme.md to `README.md`
- Refer convolution and filtering code structure ie have a `src`, `include` folders.
- Refer convolution and filtering code files and follow the similar fashion for adding the comments for the functions
- Remove the unnecessary `blob` file and not required files from the folder.

2023-03-24 12:49 UTC, Khushi-Balia commented
Made the required changes.

2023-03-24 17:04 UTC, amanchhaparia requested changes

2023-03-24 17:04 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/README.md
> +- [Detecting the blob](#detecting-the-blob)
Can be more informative if the contents in the Readme can be divided into the different topic sections similar to [this](https://github.com/SRA-VJTI/Pixels_Seminar/blob/main/3_cv_basics/6_blob_detection.ipynb)

2023-03-24 17:04 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/include/blob_detection.hpp
> +#endif
Add a new line

2023-03-24 17:04 UTC, amanchhaparia commented on 4_cv_basics/7_blob_detection/main.cpp
> +}
Add a newline

2023-03-25 15:14 UTC, Khushi-Balia commented
Updated the Readme and made the changes.

2023-03-26 08:18 UTC, aPR0T0 commented
@Khushi-Balia when we run the code for blob detection the window that pops-up is nearly my screen size, so just make it resizable and keep initial size of window smaller for better handling

2023-03-27 13:23 UTC, amanchhaparia commented
@Khushi-Balia, in the Readme content there are certain part which referred to python functions. Kindly update them. Also move `main.cpp` to `src`.

2023-03-27 16:16 UTC, Khushi-Balia commented
Made the windows resizable, updated the readme and file structure.

2023-03-27 17:53 UTC, Khushi-Balia commented
Resolved the error, made the necessary changes in the Makefile.

2023-03-27 18:52 UTC, amanchhaparia commented
@Khushi-Balia, resize is not working. I guess you need to first define the window then resize it.

2023-03-27 19:16 UTC, Khushi-Balia commented
Changed the window size and updated the readme.

2023-03-28 11:20 UTC, amanchhaparia commented
@Khushi-Balia, update the PR according to the new file structure.

2023-03-28 16:49 UTC, amanchhaparia approved these changes

2023-03-28 16:50 UTC, merged